language: c

sudo: false

cache:
  directories:
    - $HOME/travis-cache

os:
  - linux
  - osx

addons:
  apt:
    sources:
      - llvm-toolchain-precise
      - ubuntu-toolchain-r-test
    packages:
      - clang-3.7
      - gcc-5

compiler:
  - gcc
  - clang

install:
  - if [ "$CC" = "gcc" ]; then export CC="gcc-5"; fi
  - if [ "$CC" = "clang" ]; then export CC="clang-3.7"; fi

script:
  make all