language: c

notifications:
  email:
    recipients:
      - kuleshovmail@gmail.com
    on_success: change
    on_failure: always

sudo: false

cache:
  directories:
    - $HOME/travis-cache

matrix:
  include:
    - os: linux
      env: TMAIL_CC=gcc-5
      compiler: gcc-5
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['gcc-5']
    - os: linux
      env: TMAIL_CC=gcc-6
      compiler: gcc-6
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['gcc-6']
    - os: linux
      env: TMAIL_CC=clang
      compiler: clang
      addons:
        apt:
          sources: ['llvm-toolchain-precise']
          packages: ['clang-3.9']
    - os: osx
      env: TMAIL_CC=clang
      compiler: clang
    - os: osx
      env: TMAIL_CC=gcc
      compiler: gcc

git:
  depth: 1

script:
  - unset CC
  - make all
  - ./tmail -v
  - echo $?