language: c

notifications:
  email:
    recipients:
      - kuleshovmail@gmail.com
    on_success: change
    on_failure: always

sudo: false

cache:
  directories:
    - $HOME/travis-cache

matrix:
  include:
    - os: linux
      env: TMAIL_CC=gcc-7
      compiler: gcc-7
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['gcc-7', 'flex', 'bison']
    - os: linux
      env: TMAIL_CC=gcc-5
      compiler: gcc-5
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['gcc-5', 'flex', 'bison']
    - os: linux
      env: TMAIL_CC=gcc-6
      compiler: gcc-6
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['gcc-6', 'flex', 'bison']
    - os: linux
      env: TMAIL_CC=clang
      compiler: clang
      addons:
        apt:
          sources: ['llvm-toolchain-precise']
          packages: ['clang-3.9', 'flex', 'bison']
    - os: osx
      env: TMAIL_CC=clang
      compiler: clang
    - os: osx
      env: TMAIL_CC=gcc
      compiler: gcc

before_install:
  - test -n $CC && unset CC
  - 'if [[ "$TRAVIS_OS_NAME" == "osx" && "$TMAIL_CC" == "gcc" ]]; then TMAIL_CC=$(ls -t /usr/local/bin/gcc-?.*); fi'

git:
  depth: 1

script:
  - make TMAIL_CC=$TMAIL_CC V=1 all
  - make TMAIL_CC=$TMAIL_CC V=1 test