language: c

notifications:
  email:
    recipients:
      - kuleshovmail@gmail.com
    on_success: change
    on_failure: always

sudo: false

cache:
  directories:
    - $HOME/travis-cache

addons:
  apt:
    sources:
      - llvm-toolchain-precise
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - clang-3.9

matrix:
  include:
    - os: linux
      env: TMAIL_CC=gcc-4.8
      compiler: gcc-4.8
    - os: osx
      env: TMAIL_CC=clang

git:
  depth: 1

script:
  - unset CC
  - make all