language: c

notifications:
  email:
    recipients:
      - kuleshovmail@gmail.com
    on_success: change
    on_failure: always

sudo: false

cache:
  directories:
    - $HOME/travis-cache

os:
  - linux
  - osx

addons:
  apt:
    sources:
      - llvm-toolchain-precise
      - ubuntu-toolchain-r-test
    packages:
      - gcc-5
      - clang-3.9

env:
  - TMAIL_CC=clang

git:
  depth: 3

script:
  - clang --version
  - echo $LD_LIBRARY_PATH
  - LD_LIBRARY_PATH=/home/travis/build/0xAX/tmail/src/sys:$LD_LIBRARY_PATH
  - export LD_LIBRARY_PATH
  - echo $LD_LIBRARY_PATH
  - make all